// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkmLpQOsRH0FQBEAIJkjWxIwe54wCsCRs',
    appId: '1:362821979419:web:0e694bd790df8f370557be',
    messagingSenderId: '362821979419',
    projectId: 'utube-7626b',
    authDomain: 'utube-7626b.firebaseapp.com',
    storageBucket: 'utube-7626b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmNqfANlbXsVd63OLQC_Y3p0_CCY_1pjM',
    appId: '1:362821979419:android:404c5518ed825e4a0557be',
    messagingSenderId: '362821979419',
    projectId: 'utube-7626b',
    storageBucket: 'utube-7626b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7EtXGJb12pHxD9MhYfnd8HGUz3kuLlig',
    appId: '1:362821979419:ios:bfb482f81b707fed0557be',
    messagingSenderId: '362821979419',
    projectId: 'utube-7626b',
    storageBucket: 'utube-7626b.appspot.com',
    iosBundleId: 'com.example.jobTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7EtXGJb12pHxD9MhYfnd8HGUz3kuLlig',
    appId: '1:362821979419:ios:538bc4dc1e4bd2e70557be',
    messagingSenderId: '362821979419',
    projectId: 'utube-7626b',
    storageBucket: 'utube-7626b.appspot.com',
    iosBundleId: 'com.example.jobTask.RunnerTests',
  );
}
